import os from 'os';
import path from 'path';
import { execSync } from 'child_process';
import fs from 'fs';
import logger from '../utils/logger.js';

/**
 * Loragent URL Ingestion System
 * Automatically reads a system from a provided URL, identifies key needs,
 * and generates necessary Loragent agents, skills, and MCP configurations.
 */
class URLIngester {
    constructor(url) {
        this.url = url;
        // Ensure this logic dynamically targets a path outside of hardcoded structures
        this.workDir = path.join(os.homedir(), '.loragent', 'ingestion_cache', Date.now().toString());
    }

    async ingest() {
        logger.info(`🚀 Starting ingestion from: ${this.url}`);
        this.prepareEnvironment();
        this.fetchSource();
        const needs = this.analyzeSystem();
        this.generateAgentsAndSkills(needs);
        this.generateInstallInstructions();
    }

    prepareEnvironment() {
        if (!fs.existsSync(this.workDir)) {
            fs.mkdirSync(this.workDir, { recursive: true });
        }
        logger.success(`✅ Environment prepared at ${this.workDir}`);
    }

    fetchSource() {
        logger.info(`📥 Fetching source code...`);
        // Basic detection if it's a git repo
        if (this.url.endsWith('.git') || this.url.includes('github.com')) {
            execSync(`git clone ${this.url} ${this.workDir}`, { stdio: 'inherit' });
        } else {
            logger.warn(`⚠️ URL doesn't look like a standard git repository. Fallback fetch logic would go here.`);
        }
    }

    analyzeSystem() {
        logger.info(`🔍 Analyzing system dependencies and architecture...`);
        const needs = { agents: [], mcp: false, skills: [] };

        if (fs.existsSync(path.join(this.workDir, 'package.json'))) {
            logger.info(`   📦 Found Node.js project.`);
            needs.agents.push('Node.js Specialist');
            needs.mcp = true;
        }
        
        if (fs.existsSync(path.join(this.workDir, 'requirements.txt')) || fs.existsSync(path.join(this.workDir, 'pyproject.toml'))) {
            logger.info(`   🐍 Found Python project.`);
            needs.agents.push('Python Specialist');
        }

        return needs;
    }

    generateAgentsAndSkills(needs) {
        logger.info(`⚙️ Generating Agents, Skills, and MCP Configs...`);
        const agentsDir = path.join(this.workDir, '.agents', 'skills');
        fs.mkdirSync(agentsDir, { recursive: true });

        needs.agents.forEach(agent => {
            const skillContent = `---
name: ${agent.replace(/\s+/g, '-').toLowerCase()}
description: Automatically generated agent for ${agent} support.
---
# ${agent}
This agent was dynamically generated by the Loragent URL Ingester.
`;
            fs.writeFileSync(path.join(agentsDir, `SKILL-${agent.replace(/\s+/g, '')}.md`), skillContent);
            logger.success(`   ✅ Generated skill for: ${agent}`);
        });

        if (needs.mcp) {
            const mcpConfig = {
                mcpServers: {
                    "loragent-ingested": {
                        "command": "node",
                        "args": ["src/mcp/server.js"]
                    }
                }
            };
            fs.writeFileSync(path.join(this.workDir, 'mcp.json'), JSON.stringify(mcpConfig, null, 2));
            logger.success(`   ✅ Generated MCP Configuration.`);
        }
    }

    generateInstallInstructions() {
        logger.success(`\n🎉 Ingestion Complete!`);
        logger.info(`\nTo install and publish this MCP:`);
        logger.info(`1. Navigate to: cd ${this.workDir}`);
        logger.info(`2. Review the generated agents in .agents/skills/`);
        logger.info(`3. To publish your MCP, copy mcp.json to your AI IDE config folder.`);
        logger.info(`4. Run loragent to sync the new assets into your global roster.\n`);
    }
}

// CLI Execution Support
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);

if (process.argv[1] === __filename) {
    const targetUrl = process.argv[2];
    if (!targetUrl) {
        logger.error("❌ Please provide a URL to ingest.");
        process.exit(1);
    }
    const ingester = new URLIngester(targetUrl);
    ingester.ingest().catch(console.error);
}

export default URLIngester;
